stages:
  EC_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name EC_SmilesToAtoms
    params:
    - EC_SmilesToAtoms
    outs:
    - nodes/EC_SmilesToAtoms/atoms.h5
    - nodes/EC_SmilesToAtoms/molecule.png
  EC_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name EC_Packmol
    deps:
    - nodes/EC_SmilesToAtoms/atoms.h5
    - nodes/EC_SmilesToAtoms/molecule.png
    params:
    - EC_Packmol
    outs:
    - nodes/EC_Packmol/atoms.h5
    - nodes/EC_Packmol/packmol
  EC_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name EC_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/EC_Packmol/atoms.h5
    - nodes/EC_Packmol/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/EC_CP2KSinglePoint/atoms.h5
    - nodes/EC_CP2KSinglePoint/cp2k
  EC_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name EC_x10
    deps:
    - nodes/EC_CP2KSinglePoint/atoms.h5
    - nodes/EC_CP2KSinglePoint/cp2k
    - nodes/EC_Packmol/atoms.h5
    - nodes/EC_Packmol/packmol
    params:
    - EC_x10
    outs:
    - nodes/EC_x10/model_outs
    - nodes/EC_x10/optim.traj
