stages:
  BMIM_BF4_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_BF4_SmilesToAtoms
    params:
    - BMIM_BF4_SmilesToAtoms
    outs:
    - nodes/BMIM_BF4_SmilesToAtoms/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms/molecule.png
  BMIM_BF4_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_BF4_SmilesToAtoms_1
    params:
    - BMIM_BF4_SmilesToAtoms_1
    outs:
    - nodes/BMIM_BF4_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms_1/molecule.png
  BMIM_BF4_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_BF4_Packmol
    deps:
    - nodes/BMIM_BF4_SmilesToAtoms/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms/molecule.png
    - nodes/BMIM_BF4_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms_1/molecule.png
    params:
    - BMIM_BF4_Packmol
    outs:
    - nodes/BMIM_BF4_Packmol/atoms.h5
    - nodes/BMIM_BF4_Packmol/packmol
  BMIM_BF4_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_BF4_Packmol_1
    deps:
    - nodes/BMIM_BF4_Packmol/atoms.h5
    - nodes/BMIM_BF4_Packmol/packmol
    params:
    - BMIM_BF4_Packmol_1
    outs:
    - nodes/BMIM_BF4_Packmol_1/atoms.h5
    - nodes/BMIM_BF4_Packmol_1/packmol
  BMIM_BF4_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_BF4_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_BF4_Packmol_1/atoms.h5
    - nodes/BMIM_BF4_Packmol_1/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/BMIM_BF4_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_BF4_CP2KSinglePoint/cp2k
  BMIM_BF4_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_BF4_x10
    deps:
    - nodes/BMIM_BF4_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_BF4_CP2KSinglePoint/cp2k
    - nodes/BMIM_BF4_Packmol_1/atoms.h5
    - nodes/BMIM_BF4_Packmol_1/packmol
    params:
    - BMIM_BF4_x10
    outs:
    - nodes/BMIM_BF4_x10/model_outs
    - nodes/BMIM_BF4_x10/optim.traj
