stages:
  BMIM_BF4_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_BF4_SmilesToAtoms
    params:
    - BMIM_BF4_SmilesToAtoms
    outs:
    - nodes/BMIM_BF4_SmilesToAtoms/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms/molecule.png
    metrics:
    - nodes/BMIM_BF4_SmilesToAtoms/node-meta.json:
        cache: false
  BMIM_BF4_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_BF4_SmilesToAtoms_1
    params:
    - BMIM_BF4_SmilesToAtoms_1
    outs:
    - nodes/BMIM_BF4_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms_1/molecule.png
    metrics:
    - nodes/BMIM_BF4_SmilesToAtoms_1/node-meta.json:
        cache: false
  BMIM_BF4_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_BF4_Packmol
    deps:
    - nodes/BMIM_BF4_SmilesToAtoms/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms/molecule.png
    - nodes/BMIM_BF4_SmilesToAtoms/node-meta.json
    - nodes/BMIM_BF4_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_BF4_SmilesToAtoms_1/molecule.png
    - nodes/BMIM_BF4_SmilesToAtoms_1/node-meta.json
    params:
    - BMIM_BF4_Packmol
    outs:
    - nodes/BMIM_BF4_Packmol/atoms.h5
    - nodes/BMIM_BF4_Packmol/packmol
    metrics:
    - nodes/BMIM_BF4_Packmol/node-meta.json:
        cache: false
  BMIM_BF4_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_BF4_Packmol_1
    deps:
    - nodes/BMIM_BF4_Packmol/atoms.h5
    - nodes/BMIM_BF4_Packmol/node-meta.json
    - nodes/BMIM_BF4_Packmol/packmol
    params:
    - BMIM_BF4_Packmol_1
    outs:
    - nodes/BMIM_BF4_Packmol_1/atoms.h5
    - nodes/BMIM_BF4_Packmol_1/packmol
    metrics:
    - nodes/BMIM_BF4_Packmol_1/node-meta.json:
        cache: false
  BMIM_BF4_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_BF4_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_BF4_Packmol_1/atoms.h5
    - nodes/BMIM_BF4_Packmol_1/node-meta.json
    - nodes/BMIM_BF4_Packmol_1/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/BMIM_BF4_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_BF4_CP2KSinglePoint/cp2k
    metrics:
    - nodes/BMIM_BF4_CP2KSinglePoint/node-meta.json:
        cache: false
  BMIM_BF4_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_BF4_x10
    deps:
    - nodes/BMIM_BF4_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_BF4_CP2KSinglePoint/cp2k
    - nodes/BMIM_BF4_CP2KSinglePoint/node-meta.json
    - nodes/BMIM_BF4_Packmol_1/atoms.h5
    - nodes/BMIM_BF4_Packmol_1/node-meta.json
    - nodes/BMIM_BF4_Packmol_1/packmol
    params:
    - BMIM_BF4_x10
    outs:
    - nodes/BMIM_BF4_x10/model_outs
    - nodes/BMIM_BF4_x10/trajectory.h5
    metrics:
    - nodes/BMIM_BF4_x10/node-meta.json:
        cache: false
  BMIM_Cl_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_Cl_SmilesToAtoms
    params:
    - BMIM_Cl_SmilesToAtoms
    outs:
    - nodes/BMIM_Cl_SmilesToAtoms/atoms.h5
    - nodes/BMIM_Cl_SmilesToAtoms/molecule.png
    metrics:
    - nodes/BMIM_Cl_SmilesToAtoms/node-meta.json:
        cache: false
  BMIM_Cl_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_Cl_SmilesToAtoms_1
    params:
    - BMIM_Cl_SmilesToAtoms_1
    outs:
    - nodes/BMIM_Cl_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_Cl_SmilesToAtoms_1/molecule.png
    metrics:
    - nodes/BMIM_Cl_SmilesToAtoms_1/node-meta.json:
        cache: false
  BMIM_Cl_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_Cl_Packmol
    deps:
    - nodes/BMIM_Cl_SmilesToAtoms/atoms.h5
    - nodes/BMIM_Cl_SmilesToAtoms/molecule.png
    - nodes/BMIM_Cl_SmilesToAtoms/node-meta.json
    - nodes/BMIM_Cl_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_Cl_SmilesToAtoms_1/molecule.png
    - nodes/BMIM_Cl_SmilesToAtoms_1/node-meta.json
    params:
    - BMIM_Cl_Packmol
    outs:
    - nodes/BMIM_Cl_Packmol/atoms.h5
    - nodes/BMIM_Cl_Packmol/packmol
    metrics:
    - nodes/BMIM_Cl_Packmol/node-meta.json:
        cache: false
  BMIM_Cl_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_Cl_Packmol_1
    deps:
    - nodes/BMIM_Cl_Packmol/atoms.h5
    - nodes/BMIM_Cl_Packmol/node-meta.json
    - nodes/BMIM_Cl_Packmol/packmol
    params:
    - BMIM_Cl_Packmol_1
    outs:
    - nodes/BMIM_Cl_Packmol_1/atoms.h5
    - nodes/BMIM_Cl_Packmol_1/packmol
    metrics:
    - nodes/BMIM_Cl_Packmol_1/node-meta.json:
        cache: false
  BMIM_Cl_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_Cl_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_Cl_Packmol_1/atoms.h5
    - nodes/BMIM_Cl_Packmol_1/node-meta.json
    - nodes/BMIM_Cl_Packmol_1/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/BMIM_Cl_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_Cl_CP2KSinglePoint/cp2k
    metrics:
    - nodes/BMIM_Cl_CP2KSinglePoint/node-meta.json:
        cache: false
  BMIM_Cl_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_Cl_x10
    deps:
    - nodes/BMIM_Cl_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_Cl_CP2KSinglePoint/cp2k
    - nodes/BMIM_Cl_CP2KSinglePoint/node-meta.json
    - nodes/BMIM_Cl_Packmol_1/atoms.h5
    - nodes/BMIM_Cl_Packmol_1/node-meta.json
    - nodes/BMIM_Cl_Packmol_1/packmol
    params:
    - BMIM_Cl_x10
    outs:
    - nodes/BMIM_Cl_x10/model_outs
    - nodes/BMIM_Cl_x10/trajectory.h5
    metrics:
    - nodes/BMIM_Cl_x10/node-meta.json:
        cache: false
  BMIM_NTF2_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_NTF2_SmilesToAtoms
    params:
    - BMIM_NTF2_SmilesToAtoms
    outs:
    - nodes/BMIM_NTF2_SmilesToAtoms/atoms.h5
    - nodes/BMIM_NTF2_SmilesToAtoms/molecule.png
    metrics:
    - nodes/BMIM_NTF2_SmilesToAtoms/node-meta.json:
        cache: false
  BMIM_NTF2_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_NTF2_SmilesToAtoms_1
    params:
    - BMIM_NTF2_SmilesToAtoms_1
    outs:
    - nodes/BMIM_NTF2_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_NTF2_SmilesToAtoms_1/molecule.png
    metrics:
    - nodes/BMIM_NTF2_SmilesToAtoms_1/node-meta.json:
        cache: false
  BMIM_NTF2_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_NTF2_Packmol
    deps:
    - nodes/BMIM_NTF2_SmilesToAtoms/atoms.h5
    - nodes/BMIM_NTF2_SmilesToAtoms/molecule.png
    - nodes/BMIM_NTF2_SmilesToAtoms/node-meta.json
    - nodes/BMIM_NTF2_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_NTF2_SmilesToAtoms_1/molecule.png
    - nodes/BMIM_NTF2_SmilesToAtoms_1/node-meta.json
    params:
    - BMIM_NTF2_Packmol
    outs:
    - nodes/BMIM_NTF2_Packmol/atoms.h5
    - nodes/BMIM_NTF2_Packmol/packmol
    metrics:
    - nodes/BMIM_NTF2_Packmol/node-meta.json:
        cache: false
  BMIM_NTF2_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_NTF2_Packmol_1
    deps:
    - nodes/BMIM_NTF2_Packmol/atoms.h5
    - nodes/BMIM_NTF2_Packmol/node-meta.json
    - nodes/BMIM_NTF2_Packmol/packmol
    params:
    - BMIM_NTF2_Packmol_1
    outs:
    - nodes/BMIM_NTF2_Packmol_1/atoms.h5
    - nodes/BMIM_NTF2_Packmol_1/packmol
    metrics:
    - nodes/BMIM_NTF2_Packmol_1/node-meta.json:
        cache: false
  BMIM_NTF2_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_NTF2_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_NTF2_Packmol_1/atoms.h5
    - nodes/BMIM_NTF2_Packmol_1/node-meta.json
    - nodes/BMIM_NTF2_Packmol_1/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/BMIM_NTF2_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_NTF2_CP2KSinglePoint/cp2k
    metrics:
    - nodes/BMIM_NTF2_CP2KSinglePoint/node-meta.json:
        cache: false
  BMIM_NTF2_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_NTF2_x10
    deps:
    - nodes/BMIM_NTF2_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_NTF2_CP2KSinglePoint/cp2k
    - nodes/BMIM_NTF2_CP2KSinglePoint/node-meta.json
    - nodes/BMIM_NTF2_Packmol_1/atoms.h5
    - nodes/BMIM_NTF2_Packmol_1/node-meta.json
    - nodes/BMIM_NTF2_Packmol_1/packmol
    params:
    - BMIM_NTF2_x10
    outs:
    - nodes/BMIM_NTF2_x10/model_outs
    - nodes/BMIM_NTF2_x10/trajectory.h5
    metrics:
    - nodes/BMIM_NTF2_x10/node-meta.json:
        cache: false
  BMIM_PF6_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_PF6_SmilesToAtoms
    params:
    - BMIM_PF6_SmilesToAtoms
    outs:
    - nodes/BMIM_PF6_SmilesToAtoms/atoms.h5
    - nodes/BMIM_PF6_SmilesToAtoms/molecule.png
    metrics:
    - nodes/BMIM_PF6_SmilesToAtoms/node-meta.json:
        cache: false
  BMIM_PF6_AddData:
    cmd: zntrack run ipsuite.nodes.AddData --name BMIM_PF6_AddData
    deps:
    - data/pf6.xyz
    params:
    - BMIM_PF6_AddData
    outs:
    - nodes/BMIM_PF6_AddData/atoms.h5
    metrics:
    - nodes/BMIM_PF6_AddData/node-meta.json:
        cache: false
  BMIM_PF6_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_PF6_Packmol
    deps:
    - nodes/BMIM_PF6_AddData/atoms.h5
    - nodes/BMIM_PF6_AddData/node-meta.json
    - nodes/BMIM_PF6_SmilesToAtoms/atoms.h5
    - nodes/BMIM_PF6_SmilesToAtoms/molecule.png
    - nodes/BMIM_PF6_SmilesToAtoms/node-meta.json
    params:
    - BMIM_PF6_Packmol
    outs:
    - nodes/BMIM_PF6_Packmol/atoms.h5
    - nodes/BMIM_PF6_Packmol/packmol
    metrics:
    - nodes/BMIM_PF6_Packmol/node-meta.json:
        cache: false
  BMIM_PF6_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_PF6_Packmol_1
    deps:
    - nodes/BMIM_PF6_Packmol/atoms.h5
    - nodes/BMIM_PF6_Packmol/node-meta.json
    - nodes/BMIM_PF6_Packmol/packmol
    params:
    - BMIM_PF6_Packmol_1
    outs:
    - nodes/BMIM_PF6_Packmol_1/atoms.h5
    - nodes/BMIM_PF6_Packmol_1/packmol
    metrics:
    - nodes/BMIM_PF6_Packmol_1/node-meta.json:
        cache: false
  BMIM_PF6_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_PF6_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_PF6_Packmol_1/atoms.h5
    - nodes/BMIM_PF6_Packmol_1/node-meta.json
    - nodes/BMIM_PF6_Packmol_1/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/BMIM_PF6_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_PF6_CP2KSinglePoint/cp2k
    metrics:
    - nodes/BMIM_PF6_CP2KSinglePoint/node-meta.json:
        cache: false
  BMIM_PF6_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_PF6_x10
    deps:
    - nodes/BMIM_PF6_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_PF6_CP2KSinglePoint/cp2k
    - nodes/BMIM_PF6_CP2KSinglePoint/node-meta.json
    - nodes/BMIM_PF6_Packmol_1/atoms.h5
    - nodes/BMIM_PF6_Packmol_1/node-meta.json
    - nodes/BMIM_PF6_Packmol_1/packmol
    params:
    - BMIM_PF6_x10
    outs:
    - nodes/BMIM_PF6_x10/model_outs
    - nodes/BMIM_PF6_x10/trajectory.h5
    metrics:
    - nodes/BMIM_PF6_x10/node-meta.json:
        cache: false
  BMIM_NCN2_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_NCN2_SmilesToAtoms
    params:
    - BMIM_NCN2_SmilesToAtoms
    outs:
    - nodes/BMIM_NCN2_SmilesToAtoms/atoms.h5
    - nodes/BMIM_NCN2_SmilesToAtoms/molecule.png
    metrics:
    - nodes/BMIM_NCN2_SmilesToAtoms/node-meta.json:
        cache: false
  BMIM_NCN2_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_NCN2_SmilesToAtoms_1
    params:
    - BMIM_NCN2_SmilesToAtoms_1
    outs:
    - nodes/BMIM_NCN2_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_NCN2_SmilesToAtoms_1/molecule.png
    metrics:
    - nodes/BMIM_NCN2_SmilesToAtoms_1/node-meta.json:
        cache: false
  BMIM_NCN2_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_NCN2_Packmol
    deps:
    - nodes/BMIM_NCN2_SmilesToAtoms/atoms.h5
    - nodes/BMIM_NCN2_SmilesToAtoms/molecule.png
    - nodes/BMIM_NCN2_SmilesToAtoms/node-meta.json
    - nodes/BMIM_NCN2_SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_NCN2_SmilesToAtoms_1/molecule.png
    - nodes/BMIM_NCN2_SmilesToAtoms_1/node-meta.json
    params:
    - BMIM_NCN2_Packmol
    outs:
    - nodes/BMIM_NCN2_Packmol/atoms.h5
    - nodes/BMIM_NCN2_Packmol/packmol
    metrics:
    - nodes/BMIM_NCN2_Packmol/node-meta.json:
        cache: false
  BMIM_NCN2_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_NCN2_Packmol_1
    deps:
    - nodes/BMIM_NCN2_Packmol/atoms.h5
    - nodes/BMIM_NCN2_Packmol/node-meta.json
    - nodes/BMIM_NCN2_Packmol/packmol
    params:
    - BMIM_NCN2_Packmol_1
    outs:
    - nodes/BMIM_NCN2_Packmol_1/atoms.h5
    - nodes/BMIM_NCN2_Packmol_1/packmol
    metrics:
    - nodes/BMIM_NCN2_Packmol_1/node-meta.json:
        cache: false
  BMIM_NCN2_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_NCN2_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_NCN2_Packmol_1/atoms.h5
    - nodes/BMIM_NCN2_Packmol_1/node-meta.json
    - nodes/BMIM_NCN2_Packmol_1/packmol
    params:
    - cp2k.yaml:
    outs:
    - nodes/BMIM_NCN2_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_NCN2_CP2KSinglePoint/cp2k
    metrics:
    - nodes/BMIM_NCN2_CP2KSinglePoint/node-meta.json:
        cache: false
  BMIM_NCN2_x10:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_NCN2_x10
    deps:
    - nodes/BMIM_NCN2_CP2KSinglePoint/atoms.h5
    - nodes/BMIM_NCN2_CP2KSinglePoint/cp2k
    - nodes/BMIM_NCN2_CP2KSinglePoint/node-meta.json
    - nodes/BMIM_NCN2_Packmol_1/atoms.h5
    - nodes/BMIM_NCN2_Packmol_1/node-meta.json
    - nodes/BMIM_NCN2_Packmol_1/packmol
    params:
    - BMIM_NCN2_x10
    outs:
    - nodes/BMIM_NCN2_x10/model_outs
    - nodes/BMIM_NCN2_x10/trajectory.h5
    metrics:
    - nodes/BMIM_NCN2_x10/node-meta.json:
        cache: false
