EtOH-x10:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
Packmol:
    box: null
    count:
    - 10
    data_ids: null
    density: 789
    tolerance: 2.0
SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCO
