EC_Packmol:
    box: null
    count:
    - 10
    data_ids: null
    density: 1321
    tolerance: 2.0
EC_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: C1COC(=O)O1
EC_x10:
    data_id: 0
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
