BMIM_BF4_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1210
    tolerance: 2.0
BMIM_BF4_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1210
    tolerance: 2.0
BMIM_BF4_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
BMIM_BF4_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
BMIM_BF4_x10:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
BMIM_Cl_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1086
    tolerance: 2.0
BMIM_Cl_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1086
    tolerance: 2.0
BMIM_Cl_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
BMIM_Cl_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[Cl-]'
BMIM_Cl_x10:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
BMIM_NCN2_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1060
    tolerance: 2.0
BMIM_NCN2_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1060
    tolerance: 2.0
BMIM_NCN2_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
BMIM_NCN2_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: C(=[N-])=NC#N
BMIM_NCN2_x10:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
BMIM_NTF2_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1440
    tolerance: 2.0
BMIM_NTF2_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1440
    tolerance: 2.0
BMIM_NTF2_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
BMIM_NTF2_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F
BMIM_NTF2_x10:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
BMIM_PF6_AddData:
    lines_to_read: null
BMIM_PF6_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1380
    tolerance: 2.0
BMIM_PF6_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1380
    tolerance: 2.0
BMIM_PF6_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
BMIM_PF6_x10:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
